/**
 * Admin cycle & lottery management types.
 *
 * Cycle and lottery record shapes already live in `@/types` and are reused
 * verbatim. This module only adds the admin-specific request/response shapes
 * for the documented mutations:
 *   POST /committees/:cid/cycles/generate
 *   PATCH /committees/:cid/cycles/:id/status
 *   POST /committees/:cid/cycles/:cycleId/lottery/run
 *
 * Field names come straight from docs/api-documentation.md — nothing invented.
 */
import type { Cycle, LotteryResult, Member } from '@/types';

/** Response from POST /committees/:cid/cycles/generate. */
export interface GenerateCyclesResponse {
  /** Number of cycles generated by the backend. */
  generated: number;
  cycles: Cycle[];
}

/** Body for POST /committees/:cid/cycles/generate. */
export interface GenerateCyclesInput {
  committeeId: string;
  /** ISO 8601 date; overrides the committee's start date for cycle 1. */
  startDate?: string;
}

/** Args for PATCH /committees/:cid/cycles/:id/status. */
export interface UpdateCycleStatusInput {
  committeeId: string;
  id: string;
  status: 'ACTIVE' | 'COMPLETED' | 'CANCELLED';
}

/** Cycle-scoped params shared by lottery endpoints. */
export interface LotteryCycleParams {
  committeeId: string;
  cycleId: string;
}

/** Response from GET /committees/:cid/cycles/:cycleId/lottery/eligibility. */
export interface LotteryEligibility {
  eligible: boolean;
  reason: string | null;
  eligibleMemberCount: number;
}

/** Response from GET /committees/:cid/cycles/:cycleId/lottery/eligible-members. */
export interface EligibleMembersResponse {
  data: Member[];
  total: number;
}

/** Response from POST /committees/:cid/cycles/:cycleId/lottery/run and GET .../lottery/result. */
export type AdminLotteryResult = LotteryResult;
